image: microsoft/dotnet:2.2-sdk 

stages:
  - build-test

build-test:
  stage: build-test
  artifacts:
    untracked: true
  script:
    - ./etc/build/gitversion.sh
    - curl -s https://codecov.io/bash > codecov
    - chmod +x codecov
    - dotnet test --configuration Debug example.sql.tests /p:CollectCoverage=true /p:CoverletOutputFormat=opencover
    # - ./codecov -f example.messaging.core.tests/coverage.opencover.xml -t $CODECOV_TOKEN
    - dotnet pack example.sql -o $CI_PROJECT_DIR/nupkgs
    - ./etc/build/repack.sh $CI_PROJECT_DIR/nupkgs $CI_PROJECT_DIR/nupkgs.repack
    - dotnet nuget push $CI_PROJECT_DIR/nupkgs.repack/* -k $MYGET_APIKEY -s $MYGET_URL
